#visit url: http://localhost:6900/saws-server-config-dev.yaml

spring:
  application:
    name: saws-server-config
  cloud:
      config:
        server:
          git:
            uri: https://github.com/squirrelRao/saws_cluster_config_server.git
            search-paths: config
            default-label: master
            username: hqraop@163.com
            password: raoping620


server:
  port: 6900



