#visit url: http://localhost:6900/saws-server-config-dev.yaml

spring:
  application:
    name: saws-server-config
  cloud:
      config:
        server:
          git:
            uri: https://github.com/squirrelRao/saws_cluster_config_server.git
            search-paths: config
            default-label: master
            username: hqraop@163.com
            password: raoping620
  rabbit:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm: true
    publisher-returns: true
server:
  port: 6900

eureka:
  client:
    #是否将自己注册到Eureka Server,默认为true
    #由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: true
    ##是否从eureka server获取注册信息，如果不需要同步其他节点数据用false
    fetch-registry: true
    #设置服务注册中心的URL，用于client和server端交流
    healthcheck:
      enabled: true
    instance:
      hostname: server_config
      prefer-ip-address: false
      #表示eureka client间隔多久去拉取服务注册信息
      lease-renewal-interval-in-seconds: 1
      # 表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间
      lease-expiration-duration-in-seconds: 2
    server-url:
      defaultZone: http://localhost:7900/eureka/

