spring:
  application:
    name: saws-server-config
  cloud:
      config:
        server:
          git:
            uri: https://github.com/squirrelRao/saws_cluster_config_server
            username: hqraop@163.com
            password: raoping620
            default-label: master
            search-paths: config

server:
  port: 6900
